version: '3.7'

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  connectserver:
    build:
      context: ./ConnectServer
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "44405:44405"
      - "55557:55557"

  joinserver:
    build:
      context: ./JoinServer
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - mysql
    ports:
      - "55970:55970"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
